// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_j4lO2_gfaG6Qj8cV2kVwG-HPzmnEGeY',
    appId: '1:12570684441:web:e82a7dc584260b57760e88',
    messagingSenderId: '12570684441',
    projectId: 'rollcall-47d48',
    authDomain: 'rollcall-47d48.firebaseapp.com',
    storageBucket: 'rollcall-47d48.firebasestorage.app',
    measurementId: 'G-VX6RP4BE7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJqIfPhzmSyhihqi4M4hON1UvDfTqt0HA',
    appId: '1:12570684441:android:351e267ce0002da5760e88',
    messagingSenderId: '12570684441',
    projectId: 'rollcall-47d48',
    storageBucket: 'rollcall-47d48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqYymAMgtZvPm_EUt0mUAo89UIM2gJS5k',
    appId: '1:12570684441:ios:ef06232584d23ea6760e88',
    messagingSenderId: '12570684441',
    projectId: 'rollcall-47d48',
    storageBucket: 'rollcall-47d48.firebasestorage.app',
    iosBundleId: 'com.example.rollCallRPGApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqYymAMgtZvPm_EUt0mUAo89UIM2gJS5k',
    appId: '1:12570684441:ios:6d9d39e6c06680bc760e88',
    messagingSenderId: '12570684441',
    projectId: 'rollcall-47d48',
    storageBucket: 'rollcall-47d48.firebasestorage.app',
    iosBundleId: 'com.example.rollCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_j4lO2_gfaG6Qj8cV2kVwG-HPzmnEGeY',
    appId: '1:12570684441:web:b7e2e658541f618b760e88',
    messagingSenderId: '12570684441',
    projectId: 'rollcall-47d48',
    authDomain: 'rollcall-47d48.firebaseapp.com',
    storageBucket: 'rollcall-47d48.firebasestorage.app',
    measurementId: 'G-X7DR5RFB8B',
  );
}
